# Generated by Django 3.0.7 on 2020-07-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='instance_creation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminated_id', models.CharField(max_length=250)),
                ('creation_id', models.CharField(max_length=250)),
            ],
        ),
    ]
