# Generated by Django 3.0.7 on 2020-07-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0002_instance_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ami_creation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=250)),
                ('ami_id', models.CharField(max_length=250)),
            ],
        ),
    ]
