# Generated by Django 3.0.7 on 2020-07-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0003_ami_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=250)),
                ('spot_indi', models.BooleanField()),
            ],
        ),
    ]
