# Generated by Django 3.0.7 on 2020-07-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t2micro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
            ],
        ),
    ]
