# Generated by Django 3.0.7 on 2020-08-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_t2micro'),
    ]

    operations = [
        migrations.AddField(
            model_name='t2micro',
            name='fr_price',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
